version: '3'
 
services:
  ubuntu-gui:
    build:
      context: .
      dockerfile: ./gui/Dockerfile
    container_name: 'ubuntu-gui'
    tty: true
    ports:
      - 8080:80
    volumes:
          - type: bind
            source: './raw_firmwares/'
            target: '/mnt/raw_firmwares'